def css(writer):
    writer.orientation("VVHHHH")
    writer.font()
    writer.fit(0)
    writer.width(2, "6ch", True)
    writer.width(5, "20ch", False)
    writer.undisplay(2)
    writer.border_around(0)
    writer.border_mid(1,add = 1)
    writer.border_mid(4)
    writer.border0(2,"right",add=">span")
    writer.border0(2,"left",add=">span")
    writer.padding("0.4ch")
    writer.sticky(2)
    writer.header()
